[phases.setup]
nixPkgs = ["nodejs_20", "chromium", "nss", "freetype", "harfbuzz", "wget"]

[phases.install]
cmds = ["npm install"]

[start]
cmd = "PUPPETEER_EXECUTABLE_PATH=$(which chromium) node bot.js"
